name: PR Sanity Check

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses:  actions/checkout@v2
      
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Packages
        run: |
          yarn install

      - name: Lint
        run: |
          yarn lint

      - name: e2e
        run: |
          yarn build
          npx playwright install
          DEBUG=pw:api yarn test:headless

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-test-report
          path: playwright-report/
